### PR TITLE
bug fix: correcting assert within complex2hsv => adverse effects?

### LINKED ISSUE #75: utils.imsave flat array (vmin == vmax)
Whenever utils.imsave is called for a flat array (e.g. all 0j) it leads to an assertion error within complex2hsv because vmin == vmax.

### PR DESCRIPTION
**Pull request by simonesala**
Does this change cause any adverse effect anywhere else?
With this I can now also plot (e.g.) a 0j array. Should a warning for vmin == vmax be added?
This would fix #75 anyway.

### CODE REVIEW

**Comment by bjoernenders** [comment]
Thank you, Simone, for bringing this up.
Sorry Simone I was pretty busy in the new year and then had vacation. 
I read it but didn't merge it because I think vmax=vmax should be treated as an if clause to avoid division by zero. I was a bit weirded put that this fix is supposed to work and does not cause more turmoil in return.

**Comment by alexbjorling** [comment]
Sorry @simonesala and @bjoernenders but this breaks `ptypy.plot`.

It works fine with 099e071 but with c5bbf42 I get 

```
alex@w-alebjo-pc-0:~$ ptypy.plot /media/alex/C7E3-34A6/scan192_merlin_multimode_1_DM.ptyr 
Traceback (most recent call last):
  File "/home/alex/.local/bin/ptypy.plot", line 46, in <module>
    Plotter.plot_all()
  File "/home/alex/.local/lib/python2.7/site-packages/ptypy/utils/plot_client.py", line 613, in plot_all
    self.plot_storage(storage,pp, str(key), 'pr')
  File "/home/alex/.local/lib/python2.7/site-packages/ptypy/utils/plot_client.py", line 567, in plot_storage
    ptya.add_colorbar()
  File "/home/alex/.local/lib/python2.7/site-packages/ptypy/utils/plot_utils.py", line 774, in add_colorbar
    self._update_colorscale()
  File "/home/alex/.local/lib/python2.7/site-packages/ptypy/utils/plot_utils.py", line 723, in _update_colorscale
    cax.imshow(imsave(comcax), extent=[0, 1, 0, 1], aspect=self.cax_aspect)
  File "/home/alex/.local/lib/python2.7/site-packages/ptypy/utils/plot_utils.py", line 346, in imsave
    i = complex2rgb(a, vmin=vmin, vmax=vmax)
  File "/home/alex/.local/lib/python2.7/site-packages/ptypy/utils/plot_utils.py", line 191, in complex2rgb
    return hsv2rgb(complex2hsv(cin, **kwargs))
  File "/home/alex/.local/lib/python2.7/site-packages/ptypy/utils/plot_utils.py", line 176, in complex2hsv
    v = (v.clip(vmin, vmax)-vmin)/(vmax-vmin)
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
```
The problem is that even though `vmin=0.` in the arguments list, it can still get passed `None` explicitly. And it does, because the calling functions have `vmin=None` defaults and they pass on all their kwargs.

**Comment by alexbjorling** [comment]
Patched the debug_complex2hsv branch but it doesn't show up here. @bjoernenders could you merge that branch in again?

**Comment by bjoernenders** [comment]
I remerged with a small addition. Hope it works now. Thanks for reporting

**Pull request merged**
