### PR TITLE
Saving positions in ptyr output

### PR DESCRIPTION
**Pull request by alexbjorling**
Could it be as simple as this? Issue #196.

### CODE REVIEW

**Comment by bjoernenders** [comment]
Hi Alex,
I see the utility in saving the positions, but I personally would rather have a new saving type instead if enhancing the minimal type, call it "positions" or whatever.  The call to .views is unfortunately resource intensive and does not scale (currently) to large data sets. Having an alternative saving option instead of overloading the present one would isolate performance issues if they occur.
Bjoern

**Comment by alexbjorling** [comment]
Good point. I'll add a new type. But can one choose the saving type through the input parameters?

**Comment by bjoernenders** [comment]
Apparently no. You spotted a design flaw. Since a minor change is not supposed to change the input arguments, we cannot do anything about that on the master branch. So my recommendation is to add an extra kw argument for now and pass it on to the save_run call.

**Comment by aaron-parsons** [comment]
Whats the state with this PR?

**Comment by alexbjorling** [comment]
Not sure, am overwhelmed at the moment. I guess I didn't understand the last comment and left it...

**Comment by bjoernenders** [comment]
Merged in with 8af5df7

**Pull request closed without merging**
