### PR TITLE
Adds the axis grids to the saved files

### PR DESCRIPTION
**Pull request by aaron-parsons**
This just adds the axes to the saved files. This is needed for any downstream analysis of the data.

### CODE REVIEW

**Comment by aaron-parsons** [comment]
Hi Bjoern. I request a review here since saving is kind of important. Let me know what you think.

**Comment by aaron-parsons** [comment]
include #196 in this PR and merge

**Comment by alexbjorling** [comment]
Thanks Aaron, #196 and #197 were about the scanning positions, but the grids are also needed of course.

**Comment by aaron-parsons** [comment]
Hi @alexbjorling cool. Let's see if this builds. Sorry for short message, was on the phone to Bjoern at the time and I can't multitask...

**Pull request merged**
