### PR TITLE
Power correction and log-likelihood error for ePIE

### PR DESCRIPTION
**Pull request by daurer**
Small improvements for the ePIE engine, not tested with MPI.

### CODE REVIEW

**Review by bjoernenders — COMMENTED** [review]
LL is a switch, just like for DM
Power correction is ok.
Consult with Alex

**Comment by alexbjorling** [comment]
To be honest I have never used this engine, wrote it because some people here were super insistent that they needed ePIE... @daurer I guess you have used it since you are touching it up?

**Comment by daurer** [comment]
@alexbjorling thanks for the info. I have recently started testing ePIE, but more out of curiousity how it compares to the other engines and to other packages. For the data I was testing, it seemd like the probe can easily explode unless its power is constrained in some way. Therefor my suggestion to implement a power correction (similar to what we are doing in DM). 

Anybody else out there using ePIE who would be against this change?

**Comment by alexbjorling** [comment]
What I didn't like was the edge effects between domains which makes the trajectory of the  reconstruction depend on how many processes you use. But great that you're looking into it!

**Review by bjoernenders — APPROVED** [review]
Looks good, go ahead

**Pull request merged**
