### PR TITLE
Update code for parsing AMO/LCLS experiments

### PR DESCRIPTION
**Pull request by daurer**
This is the code I am currently using to parse AMO/LCLS data, would be great to have it merged into the master branch.

Thanks,
Benedikt

### CODE REVIEW

**Comment by aaron-parsons** [comment]
Is this the same as what is in #198 ? If so, can we close this one? Or should we accept this and rebase #198

**Comment by daurer** [comment]
I think this PR is ready to be merged now. Sorry for the messy history, need to improve my rebase skills.

**Comment by aaron-parsons** [comment]
ok @bjoernenders I'll let you merge this, I'll have a look at unpicking the other commits in #198. @daurer  don't worry :-) I can entirely see why you did that.

**Review by bjoernenders — APPROVED** [review]
Looks good!

**Pull request merged**
