### PR TITLE
MNT: add "ptypy" to the name of the conda envs

### PR DESCRIPTION
**Pull request by mrakitin**
Having many existing conda environments, it can be confusing to have the `core_dependencies` or `full_dependencies` environments. Adding a `ptypy` prefix to the names will help to identify the relevant environments.

### CODE REVIEW

**Comment by aaron-parsons** [comment]
Hi @mrakitin,

To get the build to pass you would also need to change the name of these files. I think this is ok to merge now.

We plan to move away from these files anyway in the nearest future, to a full conda recipe. This should mean you can more obviously install ptypy into one of your existing environments.

**Comment by mrakitin** [comment]
OK, thanks for the extra renaming commits!

**Comment by bjoernenders** [comment]
Feel free to merge, Aaron

**Comment by aaron-parsons** [comment]
Hi @mrakitin ,

Sorry. I didn't get round to this.
Could you update your fork to take into account a change I just made on master.

I'll then happily merge.

Aaron

**Comment by mrakitin** [comment]
@aaron-parsons, sorry for the late reply. I rebased on master. Please check it again.

**Comment by daurer** [comment]
merging this now, but keeping the old files for backwards compatibility (can be deleted later). @mrakitin sorry for creating a bit of a mess in your fork...

**Pull request merged**
