### PR TITLE
ePIE

### PR DESCRIPTION
**Pull request by alexbjorling**
This is now a working MPI-enabled ePIE engine, as discussed at the Southampton meeting. I've added support for all the features that are in the default parameters of BaseEngine, except for photon errors and log likelihood.

### CODE REVIEW

**Comment by alexbjorling** [comment]
Can't remember what we said at the meeting, but hope that this is a reasonable format to discuss new features before merging into master. @bjoernenders @pierrethibault

**Review by bjoernenders — APPROVED** [review]
I approve the merge. In the future we may want to put the handy feature to redistribute the data into the main Ptycho class.

**Comment by bjoernenders** [comment]
I approved. Will merge soon if no one objects.

**Comment by alexbjorling** [comment]
@aaron-parsons is this travis error caused by the environment somehow? It says it can't import yaml.

**Comment by aaron-parsons** [comment]
Hi Alex,

It's on the travis side I think. All of the travis managed repo's I develop have all come up with the same error at the same time!

Am looking into it...

Aaron

**Comment by aaron-parsons** [comment]
Hi Alex.

Fixed now. Short story is they upgraded the miniconda install so that it no longer includes pyyaml. This is stupid since it is what it uses to do the install from environment files. There may be another work around, but for now I install pyyaml outside of the environment.

If you merge master into your branch it will pick this up now.

Aaron

**Comment by alexbjorling** [comment]
Thanks, Aaron!

2016-10-28 12:27 GMT+02:00 Aaron Parsons notifications@github.com:

**Comment by alexbjorling** [comment]
fixed conflicts arising from merging pull request #59

**Pull request merged**
