### PR TITLE
fixes ml float intensities

### PR DESCRIPTION
**Pull request by aaron-parsons**
This is related to #192.

@bjoernenders @pierrethibault What do you think? Are you happy to add this field here? I'm not sure if it's a good use of the API going forward, but is the simplest fix.

### CODE REVIEW

**Comment by aaron-parsons** [comment]
Ignore this. It’s a terrible idea. I’ll look at solving this with a dictionary in the engine next week.

**Comment by aaron-parsons** [comment]
I think this is ready to merge, but I need to fix the problem with master first #191

**Comment by aaron-parsons** [comment]
This passes and can be merged @bjoernenders

**Review by bjoernenders — APPROVED** [review]
Ok I think this one is fine.

**Pull request merged**
